const mongoose = require('mongoose')

const guideSchema = new mongoose.Schema({
  imgLogoHeroSection: String,
  imgProfileHeroSection: String,
  bgHeroSection: String,
  titleHeroSection: String,
  paragraphHeroSection: String,
  btnHeroSection: String,
  btnHeroSectionLink: String,
  titleWthetahealingSection: String,
  paragraph1WthetahealingSection: String,
  paragraph2WthetahealingSection: String,
  imgWthetahealingSection: String,
  titleBenefictSection: String,
  item1BenefictSection: String,
  item2BenefictSection: String,
  item3BenefictSection: String,
  item4BenefictSection: String,
  item5BenefictSection: String,
  imgBenefictSection: String,
  titleWlthetahealingSection: String,
  item1WlthetahealingSection: String,
  item2WlthetahealingSection: String,
  item3WlthetahealingSection: String,
  item4WlthetahealingSection: String,
  btnWlthetahealingSection: String,
  btnWlthetahealingSectionLink: String,
  titleAvideoSection: String,
  paragraphAvideoSection: String,
  imgAvideoSection: String,
  titlev1AvideoSection: String,
  imgv1AvideoSection: String,
  pv1AvideoSection: String,
  titlev2AvideoSection: String,
  imgv2AvideoSection: String,
  pv2AvideoSection: String,
  titlev3AvideoSection: String,
  imgv3AvideoSection: String,
  pv3AvideoSection: String,
  titlev4AvideoSection: String,
  imgv4AvideoSection: String,
  pv4AvideoSection: String,
  titlev5AvideoSection: String,
  imgv5AvideoSection: String,
  pv5AvideoSection: String,
  imgAuthorSection: String,
  p1AuthorSection: String,
  p2AuthorSection: String,
  p3AuthorSection: String,
  p4AuthorSection: String,
  nameAuthorSection: String,
  propAuthorSection: String,
  btnAuthorSection: String,
  btnAuthorSectionLink: String,
  titleTestimonialSection: String,
  t1p1TestimonialSection: String,
  t1p2TestimonialSection: String,
  t1p3TestimonialSection: String,
  t2p1TestimonialSection: String,
  t2p2TestimonialSection: String,
  t2p3TestimonialSection: String,
  t3p1TestimonialSection: String,
  t3p2TestimonialSection: String,
  t3p3TestimonialSection: String,
  imgTestimonialSection: String,
  pln1PlanSection: String,
  pln1vPlanSection: String,
  pln1i1PlanSection: String,
  pln1i2PlanSection: String,
  pln1i3PlanSection: String,
  pln1btnPlanSection: String,
  pln1btnPlanSectionLink: String,
  pln2PlanSection: String,
  pln2vPlanSection: String,
  pln2i1PlanSection: String,
  pln2i2PlanSection: String,
  pln2i3PlanSection: String,
  pln2i4PlanSection: String,
  pln2btnPlanSection: String,
  pln2btnPlanSectionLink: String,
  pln3PlanSection: String,
  pln3vPlanSection: String,
  pln3i1PlanSection: String,
  pln3i2PlanSection: String,
  pln3i3PlanSection: String,
  pln3i4PlanSection: String,
  pln3i5PlanSection: String,
  pln3i6PlanSection: String,
  pln3btnPlanSection: String,
  pln3btnPlanSectionLink: String,
  titleFaqSection: String,
  ask1FaqSection: String,
  answer1FaqSection: String,
  ask2FaqSection: String,
  answer2FaqSection: String,
  ask3FaqSection: String,
  answer3FaqSection: String,
  ask4FaqSection: String,
  answer4FaqSection: String,
  titleContactSection: String,
  paragraphContactSection: String,
  iconContactSection: String,
  linkContactSection: String,
})

guideSchema.set('toJSON', {
  transform: (document, returnedObject) => {
    returnedObject.id = returnedObject._id.toString()
    delete returnedObject._id
    delete returnedObject.__v
  }
})

module.exports = mongoose.model('Guide', guideSchema)